Add usable prefix to default configuration
serenity-rs/serenity pull request #1041
Opened 2020-10-27 14:31 UTC by Qeenon

Not sure but for me it looks more consistent since there is default `Delimiter` and I was thinking that default configuration should be usable without changes, now it's not seems like because on_mention is disabled and prefix is not set.
I've picked ! because I think that it's widely used.

2020-10-27 14:47 UTC, Flat requested changes
This line needs updated to state the new default https://github.com/serenity-rs/serenity/blob/d565058380249e88bc98a583c17fe8a18efef908/src/framework/standard/configuration.rs#L407

Additionally most of the framework examples use `~` as a prefix. I think this either needs to be the default or the examples updated to `!` it should also be mentioned that you can set no prefix by passing an empty vec i.e. `.prefix(vec![])`

2020-10-27 20:00 UTC, Qeenon commented
didn't knew about `~` will change on it tomorrow, some later

2020-10-28 11:10 UTC, Flat approved these changes

2020-10-28 18:05 UTC, acdenisSK requested changes

2020-10-28 18:05 UTC, acdenisSK commented on src/framework/standard/configuration.rs
> +            };
Formatting nitpick.
```suggestion
        self.prefixes = if prefix.is_empty() {
            vec![]
        } else {
            vec![prefix.to_string()]
        };
```

2020-10-28 18:53 UTC, acdenisSK approved these changes

2020-10-28 18:54 UTC, merged