Sending files with webhooks
serenity-rs/serenity pull request #1071
Opened 2020-11-09 19:01 UTC by JellyWX

To address issue #1066 .

I only set this up for one file since I didn't realize initially that webhooks support multiple files

2020-11-09 20:17 UTC, acdenisSK requested changes

2020-11-09 20:17 UTC, acdenisSK commented on src/http/client.rs
> +        where T: Into<AttachmentType<'a>> {
Formatting nitpick.

```suggestion
        map: JsonMap
    ) -> Result<Option<Message>>
        where 
            T: Into<AttachmentType<'a>>,
    {
```

2020-11-09 20:17 UTC, acdenisSK commented on src/http/client.rs
> +
```suggestion
```

2020-11-09 20:46 UTC, JellyWX commented
that should resolve changes. there's a couple of notes id like to add though (since I could resolve them/change what ive done off what you suggest):

* the code is adapted from the `send_files` method. However, to avoid using a new `unsafe` block, I used `files.into_iter().enumerate()`. it would be trivial to modify `send_files` to remove the unsafe block from there, but i presume it is there for a good reason? see:


        let mut file_num = "0".to_string();

        for file in files {
            ...
            
            unsafe {
                let vec = file_num.as_mut_vec();
                vec[0] += 1;
            }
        }


* also, `send_files` has this loop towards the end (which is also accompanied by some code in the calling method that modifies the map before it is passed in). I have replaced both of those with a single line in the webhook one. see original:


        for (k, v) in map {
            match v {
                Value::Bool(false) => multipart = multipart.text(k.clone(), "false"),
                Value::Bool(true) => multipart = multipart.text(k.clone(), "true"),
                Value::Number(inner) => multipart = multipart.text(k.clone(), inner.to_string()),
                Value::String(inner) => multipart = multipart.text(k.clone(), inner),
                Value::Object(inner) => multipart = multipart.text(k.clone(), serde_json::to_string(&inner)?),
                _ => continue,
            };
        }


see modified:
 

        multipart = multipart.text("payload_json", serde_json::to_string(&map)?);

2020-11-09 22:59 UTC, acdenisSK approved these changes
Tested locally, function works as expected. You can apply those changes you did to the normal `send_files` function if you wish.

2020-11-10 14:04 UTC, acdenisSK approved these changes

2020-11-10 14:04 UTC, merged