Add initial support for stickers
serenity-rs/serenity pull request #1078
Opened 2020-11-14 06:22 UTC by drklee3

Not exactly tested yet against the API other than `cargo test --all-features` since I don't have stickers available to use nor do I know anyone with stickers. 😬 

For reference, discord/discord-api-docs#2155 has just been merged.

2020-12-09 23:33 UTC, KamranMackey requested changes
Looking good, just a few mentions with regards to the use of `_nonexhaustive` vs the `#[non_exhaustive]` attribute.

2020-12-09 23:33 UTC, KamranMackey commented on src/cache/mod.rs
> +                _nonexhaustive: (),
Please remove this; serenity was moved to `#[non_exhaustive]` a few days ago, meaning this is no longer needed.

2020-12-09 23:33 UTC, KamranMackey commented on src/model/channel/sticker.rs
> +    pub(crate) _nonexhaustive: (),
Same thing here. Please remove `_nonexhaustive` in favor of the `#[non_exhaustive]` attribute.

2020-12-09 23:33 UTC, KamranMackey commented on src/utils/custom_message.rs
> +        _nonexhaustive: (),
This as well to prevent the `dummy_message()` function from breaking.

2020-12-10 05:55 UTC, KamranMackey approved these changes
LGTM 👍🏻

2020-12-10 19:17 UTC, faith approved these changes

2020-12-16 13:34 UTC, Flat approved these changes

2020-12-16 13:35 UTC, Lakelezz requested changes
Thank your for your pull request.

I added some small changes :)

2020-12-16 13:35 UTC, Lakelezz commented on src/model/channel/sticker.rs
> +/// A sticker sent with a message
```suggestion
/// A sticker sent with a message.
```
Just to add the fullstop.

2020-12-16 13:35 UTC, Lakelezz commented on src/model/channel/sticker.rs
> +/// Bots currently can only receive messages with stickers, not send
```suggestion
/// Bots currently can only receive messages with stickers, not send.
```
Adding another fullstop.

2020-12-16 13:35 UTC, Lakelezz commented on src/model/channel/sticker.rs
> +/// Differentiates between sticker formats
```suggestion
/// Differentiates between sticker formats.
```
Added missing fullstop.

2020-12-16 13:35 UTC, Lakelezz commented on src/model/channel/sticker.rs
> +}
```suggestion
pub enum StickerFormatType {
    /// A PNG format sticker.
    Png = 1,
    /// An APNG format animated sticker.
    Apng = 2,
    /// A LOTTIE format animated sticker.
    Lottie = 3,
}
```

Enum variants are supposed to be `PascalCase`.

2020-12-16 13:35 UTC, Lakelezz commented on src/model/channel/sticker.rs
> +    }
```suggestion
    StickerFormatType {
        Png,
        Apng,
        Lottie,
    }
```
Enum variants are supposed to be `PascalCase`.

2020-12-16 13:35 UTC, Lakelezz commented on src/model/channel/sticker.rs
> +        }
```suggestion
        match self {
            Png => 1,
            Apng => 2,
            Lottie => 3,
        }
```
Enum variants are supposed to be `PascalCase`.

2020-12-16 21:07 UTC, Lakelezz approved these changes

2020-12-16 21:07 UTC, merged