Fix for #1050 (member fetching default limit & validation)
serenity-rs/serenity pull request #1091
Opened 2020-11-28 12:10 UTC by SadiinsoSnowfall

Fix #1050 by using the maximum value (1000) as the default value for the member fetch limit and by validating the limit value before sending the request.
This version passed all the tests and ran successfully on a real discord bot.

This may be considered a breaking change as it will change the behaviour of the `guild_id::members`, `Guild::members` and `PartialGuild::members` functions when passing an invalid value or None as the limit.

2020-12-16 13:27 UTC, Lakelezz requested changes
Thanks for your pull request. 
I just put in some small improvements to the wording of the original doc, but since we are already there, let's improve them as well!

2020-12-16 13:27 UTC, Lakelezz commented on src/error.rs
> +    /// Input is not in the specified range
```suggestion
    /// The input is not in the specified range.
```
Just a small nit.

2020-12-17 09:15 UTC, Lakelezz commented
Thanks for merging my suggestions, make sure to resolve the conflict!

2020-12-19 11:49 UTC, SadiinsoSnowfall commented
My apologies for the delay, it should be good now.

2020-12-19 11:50 UTC, KamranMackey approved these changes

2020-12-19 12:17 UTC, merged

2020-12-19 12:17 UTC, Lakelezz commented
Thank you for your pull request!