Add builders for creating interactions
serenity-rs/serenity pull request #1186
Opened 2021-01-12 20:39 UTC by Th3-M4jor

While this is grossly incomplete, and still needs a lot more documentation,
I would like to get feedback on what's there before continuing.

2021-01-13 21:31 UTC, Th3-M4jor commented
I believe this is ready for review.
Could add functions for creating and sending these to `model::interactions` but I think that should wait until after #1175 is merged

2021-01-17 12:53 UTC, acdenisSK requested changes
This is good, but is there a reason the target branch is `next`? I don't see why this addition should have to be released in 0.11.

2021-01-17 12:53 UTC, acdenisSK commented on src/builder/create_interaction.rs
> +        self
```suggestion
        self.add_sub_option(data)
```

2021-01-17 12:53 UTC, acdenisSK commented on src/builder/create_interaction.rs
> +        self
```suggestion
        self.add_interaction_option(data)
```

2021-01-17 15:42 UTC, Th3-M4jor commented
You're right, this can be switched from `next` to `current`.

2021-01-17 16:40 UTC, acdenisSK approved these changes

2021-01-17 16:54 UTC, acdenisSK commented
Manually rebased onto `current`: https://github.com/serenity-rs/serenity/commit/0d743fdd3b7cc0ea28500547ff0a9caff4a83c3f

2021-01-17 16:54 UTC, closed without merging