Ignore Missing Cache Items on Permission Checks
serenity-rs/serenity pull request #1233
Opened 2021-02-18 19:09 UTC by Lakelezz

# Description
When the cache is enabled but the cache is not populated with all the data needed for a permission check, the check failed with an error.
This pull request changes model methods to run the HTTP-request still, as attempting to run the request is cheaper than requesting data for a check.

# Type of Change
This pull request qualifies as a *fix*, relates to code residing in the *utils* and *model*, and closes #1166.
It fixes the behaviour, as the methods were never truly designed to fail, nonetheless, the new gateway intents causes the cache to receive fewer events by default.

# How Has This Been Tested?
Attempted to run some of these methods that would run a permission check while the gateway intents are disabled.
I would be happy if people can try to run their bots with this pull request, especially if you encountered #1166,

2021-02-18 19:33 UTC, acdenisSK requested changes

2021-02-18 19:33 UTC, acdenisSK commented on src/model/utils.rs
> +/// Unline [`user_has_perms`], this function will return `true` even when
Typo.
```suggestion
/// Unlike [`user_has_perms`], this function will return `true` even when
```

2021-02-18 19:36 UTC, Lakelezz commented on src/model/utils.rs
> +/// Unline [`user_has_perms`], this function will return `true` even when
That's a funny one!

2021-02-19 19:02 UTC, acdenisSK approved these changes

2021-02-20 14:59 UTC, Flat approved these changes

2021-02-23 15:49 UTC, merged