feat(model): Add `rtc_region` and `video_quality_mode` guildchannel fields
serenity-rs/serenity pull request #1276
Opened 2021-04-01 21:19 UTC by drklee3

#### Description

Adds new fields `rtc_region` and `video_quality_mode` to `GuildChannel`.

Documentation:

- rtc_region: https://github.com/discord/discord-api-docs/pull/2692
- video_quality_mode: https://github.com/discord/discord-api-docs/pull/2754

#### Tested

`cargo test --all-features` passes.  

Basic test using `ChannelId(channel_id)to_channel(&ctx).await` shows deserialization works with a `rtc_region` override set and `video_quality_mode` set to 720p in channel settings:

2021-04-01 23:07 UTC, FelixMcFelix requested changes
Thanks for this. I think there's just a point on semantics to clear up in the docs, but beyond that LGTM!

2021-04-01 23:07 UTC, FelixMcFelix commented on src/model/channel/guild_channel.rs
> +    ///
Would you be able to clarify here that a `None` value on this field for a compatible channel (voice/stage) means automatic region selection?

2021-04-02 10:40 UTC, FelixMcFelix approved these changes

2021-04-02 13:23 UTC, acdenisSK approved these changes

2021-04-02 13:24 UTC, merged