Better errors display
serenity-rs/serenity pull request #1310
Opened 2021-04-29 14:08 UTC by HarmoGlace

This PR improves the error system which was introduced in v8: https://discord.com/developers/docs/reference#error-messages

It gives an additionnal `errors` field which lists each problematic field with an error code, message and a path to this field in the request.

It was tested.

2021-04-29 16:05 UTC, kangalioo commented
This is great! The somewhat obscure error messages were an annoyance to display coherently to the user, which is hopefully much easier and better now!

2021-04-29 16:22 UTC, HarmoGlace commented
> This is great! The somewhat obscure error messages were an annoyance to display coherently to the user, which is hopefully much easier and better now!

Indeed, it is less readable but much more easier to debug, as it also support several errors and does not show to only one of it, and with a path the developer can immediatly know where is his error coming from.
![image](https://user-images.githubusercontent.com/23212967/116584410-9ab7a280-a917-11eb-8a69-e2f7d40792d3.png)

2021-04-29 16:22 UTC, acdenisSK requested changes

2021-04-29 16:22 UTC, acdenisSK commented on src/http/error.rs
> +// }
```suggestion
```

2021-04-30 15:22 UTC, acdenisSK approved these changes

2021-04-30 15:24 UTC, merged