New Discord Certified Moderator Flag Add
serenity-rs/serenity pull request #1351
Opened 2021-05-20 03:55 UTC by Max2408

Description: This pull request adds the Discord Certified Moderator badge flag to the User Flags

Justification: PR in discord-api-docs: https://github.com/discord/discord-api-docs/pull/2946

2021-05-20 21:18 UTC, HarmoGlace requested changes

2021-05-20 21:18 UTC, HarmoGlace commented on src/model/user.rs
> +        DISCORD_CERTIFIED_MODERATOR = 0b0000_0000_0000_0000_0010 0000 0000_0000;
```suggestion
        DISCORD_CERTIFIED_MODERATOR = 0b0000_0000_0000_0100_0000_0000_0000_0000;
```

2021-05-21 14:01 UTC, Max2408 commented
Now you can merge it i fixed it problem

2021-05-21 14:02 UTC, HarmoGlace approved these changes

2021-05-21 14:18 UTC, acdenisSK approved these changes

2021-05-21 14:19 UTC, merged