Add support for fetching the current user's connections
serenity-rs/serenity pull request #1401
Opened 2021-06-23 21:02 UTC by Dinnerbone

Allows fetching of the current users connections to third party services, which are shown on the profile.

This requires a user token - not a bot token - and the `connections` scope.

Example output:
```rust
[
    Connection {
        id: "Dinnerbone#0000",
        name: "Dinnerbone#0000",
        kind: "battlenet",
        revoked: None,
        integrations: None,
        verified: true,
        friend_sync: true,
        show_activity: true,
        visibility: Everyone,
    },
    Connection {
        id: "317625",
        name: "Dinnerbone",
        kind: "github",
        revoked: None,
        integrations: None,
        verified: true,
        friend_sync: false,
        show_activity: true,
        visibility: Everyone,
    }
],
```

2021-06-23 21:09 UTC, HarmoGlace commented on src/model/connection.rs
> +    pub revoked: Option<bool>,
```suggestion
    #[serde(default)]
    pub revoked: Option<bool>,
```

2021-06-23 21:13 UTC, HarmoGlace requested changes
Thanks for the PR, here are some minor changes/typos

2021-06-23 21:13 UTC, HarmoGlace commented on src/model/connection.rs
> +    pub integrations: Option<Vec<Integration>>,
```suggestion
    [#[serde(default)]
    pub integrations: Option<Vec<Integration>>,
```

2021-06-23 21:13 UTC, HarmoGlace commented on src/model/connection.rs
> +    /// The visibility of this connection
```suggestion
    /// The visibility of this connection.
```

2021-06-23 21:13 UTC, HarmoGlace commented on src/model/connection.rs
> +/// The visibility of a user connection on a users profile.
```suggestion
/// The visibility of a user connection on a user's profile.
```

2021-06-23 21:32 UTC, HarmoGlace approved these changes

2021-06-25 17:58 UTC, acdenisSK approved these changes

2021-06-25 17:59 UTC, merged