Add a set_component method to respective builders
serenity-rs/serenity pull request #1406
Opened 2021-06-25 13:49 UTC by JellyWX

2021-06-25 13:51 UTC, JellyWX commented
Certain I ran cargofmt.....

2021-07-04 16:30 UTC, HarmoGlace requested changes
Please run cargo fmt

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_interaction_response.rs
> +    /// Create components for this message.
```suggestion
    /// Creates components for this message.
```

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_interaction_response_followup.rs
> +    /// Create components for this message.
```suggestion
    /// Creates components for this message.
```

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_interaction_response.rs
>      #[cfg(feature = "unstable_discord_api")]
```suggestion
```
(It was not introduced in this PR but it is useless to have it in this builder)

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_interaction_response.rs
> +    #[cfg(feature = "unstable_discord_api")]
```suggestion
```

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_interaction_response_followup.rs
>      #[cfg(feature = "unstable_discord_api")]
```suggestion
```

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_interaction_response_followup.rs
> +    #[cfg(feature = "unstable_discord_api")]
```suggestion
```

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_message.rs
> +    /// Create components for this message.
```suggestion
    /// Creates components for this message.
```

2021-07-04 16:30 UTC, HarmoGlace commented on src/builder/create_message.rs
> +    #[cfg(feature = "unstable_discord_api")]
```suggestion
```

2021-08-12 07:43 UTC, JellyWX commented
Sorry, been busy the last month. Think this should have sorted all of that despite having a slight git nightmare

2021-08-23 10:33 UTC, HarmoGlace approved these changes

2021-08-23 11:43 UTC, acdenisSK approved these changes

2021-08-23 11:44 UTC, merged