Added a simple dashboard example.
serenity-rs/serenity pull request #1476
Opened 2021-08-23 17:25 UTC by vicky5124

This PR adds an example for a bot dashboard, using RillRate

	modified:   .github/workflows/ci.yml
	modified:   Cargo.toml
	modified:   Makefile.toml
	modified:   examples/README.md
	new file:   examples/e15_simple_dashboard/Cargo.toml
	new file:   examples/e15_simple_dashboard/Makefile.toml
	new file:   examples/e15_simple_dashboard/example video.mp4
	new file:   examples/e15_simple_dashboard/src/main.rs

2021-09-10 17:13 UTC, acdenisSK requested changes

2021-09-10 17:13 UTC, acdenisSK commented on examples/e15_simple_dashboard/src/main.rs
> +        // with the name of the create you are using it with.
```suggestion
        // with the name of the crate you are using it with.
```

2021-09-10 17:22 UTC, nickelc commented
I think the 5.6 MB big example video shouldn't be included and hosted elsewhere.

2021-09-10 17:30 UTC, acdenisSK commented
I agree. I should have touched upon that when I was submitting my review. Git isn't built for binary files; its job is to manage history of text files, particularly source code. If the video is committed into the repository, it will be forever there, even if we remove it later, unless we alter history.

2021-09-11 08:35 UTC, vicky5124 commented
The example video has been deleted on 1b9f819

2021-09-11 12:49 UTC, acdenisSK approved these changes

2021-09-11 12:50 UTC, merged