Support for Webhooks posting to threads
serenity-rs/serenity pull request #1478
Opened 2021-08-26 21:49 UTC by breezystatic77

Added the `thread_id` method to the webhook builder. When called, it adds the `thread_id` query string param to the Webhook execution, in line with the [Discord documentation](https://discord.com/developers/docs/resources/webhook#execute-webhook)

```rust
// post to the guild channel
webhook.execute(&http. false, |mut w| w.content("test").username("serenity"));

// post to a specific thread in the guild channel
webhook.execute(&http. false, |mut w| w.content("test").username("serenity").thread_id(880515904499253249));
```

Additionally, added a line to the documentation for `GuildChannel.category_id` clarifying how it represents the parent text channel id when the channel is a thread. [Documentation](https://discord.com/developers/docs/topics/threads#new-thread-fields) says that the `parent_id` field is reused this way.

2021-08-26 22:20 UTC, Zaitara requested changes

2021-08-26 22:20 UTC, Zaitara commented on src/builder/execute_webhook.rs
> -pub struct ExecuteWebhook<'a>(pub HashMap<&'static str, Value>, pub Vec<AttachmentType<'a>>);
Renaming these fields is a breaking change. You can't do it if you are targeting `current`, you can either keep the previous naming or rebase on `next`

2021-08-27 06:23 UTC, AldanTanneo commented on src/model/channel/guild_channel.rs
> +    /// When this channel is a thread, this Id corresponds to the thread's parent text channel instead.
This doc change should go to `category_id`, not on the channel's Id

2021-08-27 06:24 UTC, AldanTanneo commented on src/builder/execute_webhook.rs
> +    pub thread_id: Option<u64>,
Why is it not a `ChannelId`?

2021-08-27 09:49 UTC, Zaitara requested changes

2021-08-27 09:49 UTC, Zaitara commented on src/http/routing.rs
> +    ) -> String
This is also a breaking change.

2021-08-27 09:49 UTC, Zaitara commented on src/http/routing.rs
> +        }
```suggestion
       let mut path = format!(api!("/webhooks/{}/{}?wait={}"),
                webhook_id, token, wait);

       if let Some(thread_id) = thread_id {
          let _ = write!(path, "&thread_id=", thread_id);
   }

path
        
```

(You'll need to reformat it)

2021-09-18 22:45 UTC, breezystatic77 commented
I can't really think of a clean way to do this without breaking changes, especially to `ExecuteWebhook.` It'll have to be a change to `next`.

2021-09-18 22:45 UTC, closed without merging

2022-03-15 04:55 UTC, axonasif commented
Hey guys, was this added in any branch?