implement defer helper method
serenity-rs/serenity pull request #1517
Opened 2021-09-28 16:41 UTC by Milo123459

fixes #1516

2021-09-28 17:24 UTC, Milo123459 commented
Looks like the reason it is failing is because of the broken CI. Should be fixed by #1518

2021-09-29 18:02 UTC, Milo123459 commented
@acdenisSK what do you think? I'm not sure if this goes against serenity "design plan" or whatever but I think this is a good addition.

2021-09-29 18:22 UTC, acdenisSK requested changes

2021-09-29 18:22 UTC, acdenisSK commented on src/model/interactions/application_command.rs
> +            f.kind(InteractionResponseType::DeferredUpdateMessage)
```suggestion
            f.kind(InteractionResponseType::DeferredChannelMessageWithSource)
```

2021-09-29 18:24 UTC, Milo123459 commented on src/model/interactions/application_command.rs
> +            f.kind(InteractionResponseType::DeferredUpdateMessage)
Oops..

2021-10-03 07:48 UTC, Milo123459 commented
Any changes needed?

2021-10-03 08:44 UTC, acdenisSK approved these changes

2021-10-03 08:45 UTC, merged