Fix CI
serenity-rs/serenity pull request #1518
Opened 2021-09-28 16:45 UTC by Milo123459

This PR fixes the CI currently failing.

2021-09-28 17:13 UTC, acdenisSK requested changes

2021-09-28 17:13 UTC, acdenisSK commented on .github/workflows/ci.yml
> +      - name: FMT
```suggestion
      - name: Format
```

2021-09-28 17:54 UTC, Milo123459 commented
Opened upstream issue: https://github.com/rust-lang/rust-clippy/issues/7735

2021-10-04 17:21 UTC, Milo123459 commented
https://github.com/rust-lang/rust-clippy/issues/7712 has been closed, when it comes out on nightly this can be merged

2021-10-04 17:27 UTC, nickelc commented
Hmm, i don't see how moving the lint jobs to test build matrix would have fixed the issues

2021-10-04 17:30 UTC, Milo123459 commented
Perhaps this  was the wrong name; this should just be some changes to the CI

2021-10-04 17:43 UTC, nickelc commented
The clippy & format are separated because they run faster than the test build matrix and the clippy job also post annotations of the clippy warnings.

So, you get a faster response to PRs without interfering the test build matrix.

2021-10-04 17:48 UTC, Milo123459 commented
Oh

2021-10-04 17:48 UTC, closed without merging