Add channel types to slash commands
serenity-rs/serenity pull request #1537
Opened 2021-10-07 18:46 UTC by vicky5124

https://github.com/discord/discord-api-docs/commit/0a4c2fe7ff57828dbacd9f57f39331cf510c56af
Limits the channels that show up on channel type arguments in slash commands.

	modified:   src/builder/create_application_command.rs
	modified:   src/model/channel/mod.rs
	modified:   src/model/interactions/application_command.rs

2021-10-07 18:54 UTC, arqunis requested changes

2021-10-07 18:54 UTC, arqunis commented on src/builder/create_application_command.rs
> +    pub fn add_channel_types(&mut self, channel_types: Vec<ChannelType>) -> &mut Self {
Name should be just `channel_types`, because we have established that `add_*` methods on builders will append data, not overwrite. The option type `Channel` should also be referenced, just like in the above method's documentation.
```suggestion
    /// If the option is a [`Channel`], it will only be able to show these types.
    ///
    /// [`Channel`]: crate::model::interactions::application_command::ApplicationCommandOptionType::Channel
    pub fn channel_types(&mut self, channel_types: Vec<ChannelType>) -> &mut Self {
```

2021-10-07 18:54 UTC, arqunis commented on src/model/interactions/application_command.rs
> +    /// If an option is a Channel type, it will only be able to show these types.
```suggestion
    /// If the option is a [`Channel`], it will only be able to show these types.
    ///
    /// [`Channel`]: ApplicationCommandOptionType::Channel
```

2021-10-08 06:56 UTC, kangalio commented on src/builder/create_application_command.rs
> +    pub fn channel_types(&mut self, channel_types: Vec<ChannelType>) -> &mut Self {
Could this take `&[ChannelType]` instead?

2021-10-09 11:51 UTC, vicky5124 commented on src/builder/create_application_command.rs
> +    pub fn channel_types(&mut self, channel_types: Vec<ChannelType>) -> &mut Self {
Because it gets mapped, this was possible to do in 55ce06b09

2021-10-09 12:09 UTC, arqunis approved these changes

2021-10-09 12:12 UTC, merged