Add ClientBuilder::get_token(&self) -> &str
serenity-rs/serenity pull request #1550
Opened 2021-10-13 19:28 UTC by kangalio

This method is useful e.g. for a discord bot framework I'm writing, where the user can pass a ClientBuilder into the framework constructor. With access to the token, the framework can extract the bot user ID from the token which is needed for e.g. using bot mention as a prefix.

Anyways, I implemented this by replacing the two fields `token: Option<String>, http: Option<Http>` with just `http: Http`:
- the Http struct contains the token anyways
- removing the unneeded Option's means that get_token can return &str instead of Option<&str>

2021-10-15 17:17 UTC, arqunis requested changes

2021-10-15 17:17 UTC, arqunis commented on src/client/mod.rs
> +    pub fn get_token(&self) -> &str {
There should be some documentation here.
```suggestion
    /// Gets the current token used for the [`Http`] client.
    ///
    /// [`Http`]: crate::http::Http 
    pub fn get_token(&self) -> &str {
```

2021-10-15 17:17 UTC, arqunis commented on src/client/mod.rs
> +            let http = Arc::new(std::mem::replace(&mut self.http, Default::default()));
[`std::mem::take`][take] can be used instead. It performs same work as this `replace` call here, but is simpler to use and shortens the code a bit. 
```suggestion
            let http = Arc::new(std::mem::take(&mut self.http));
```

[take]: https://doc.rust-lang.org/stable/std/mem/fn.take.html

2021-10-16 15:09 UTC, arqunis approved these changes
[Seems like there's an extra space from my documentation suggestion](https://github.com/serenity-rs/serenity/pull/1550/checks?check_run_id=3908748445), sorry. Could you remove it? Otherwise, the PR is good to be merged.

2021-10-16 18:47 UTC, kangalioo commented
Done

2021-10-16 18:48 UTC, merged