Implement Ord and PartialOrd for Timestamp
serenity-rs/serenity pull request #1882
Opened 2022-05-01 19:35 UTC by tedtramonte

Closes #1881

2022-05-01 19:50 UTC, acdenisSK requested changes

2022-05-01 19:50 UTC, acdenisSK commented on src/model/timestamp.rs
> +        Some(self.unix_timestamp().cmp(&other.unix_timestamp()))
Since the implementation is the same, we can implement `PartialOrd` in terms of `Ord`:
```suggestion
        Some(self.cmp(other))
```

2022-05-01 20:04 UTC, tedtramonte commented
Thanks for the tip. I changed that and squashed, adding you as a co-author.

2022-05-01 20:07 UTC, vaporox commented
Since both possible inner structs implement `Ord` (see [`chrono`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#impl-Ord) / [`time`](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#impl-Ord)), I believe you should be able to just derive it instad of manually implementing

2022-05-01 20:08 UTC, tedtramonte commented
> Since both possible inner structs implement `Ord` (see [`chrono`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#impl-Ord) / [`time`](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#impl-Ord)), I believe you should be able to just derive it instad of manually implementing

I thought the same, but Clippy was SCREAMING at me for even thinking of doing that. That's how I tried it originally. Perhaps I was doing something wrong, though.

2022-05-01 20:15 UTC, nickelc commented
> > Since both possible inner structs implement `Ord` (see [`chrono`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#impl-Ord) / [`time`](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#impl-Ord)), I believe you should be able to just derive it instad of manually implementing
> 
> I thought the same, but Clippy was SCREAMING at me for even thinking of doing that. That's how I tried it originally. Perhaps I was doing something wrong, though.

I don't know. clippy is quiet for me when deriving `PartialOrd` and `Ord`.

Can you post the error message?

2022-05-01 20:20 UTC, tedtramonte commented
@nickelc Sorry, not clippy complaining, it's the compiler.

```
error: lifetime may not live long enough
    --> src\model\guild\mod.rs:1634:33
     |
1630 |           &self,
     |           - let's call the lifetime of this reference `'1`
1631 |           prefix: &str,
     |                   - let's call the lifetime of this reference `'2`
...
1634 |       ) -> Vec<(&Member, String)> {
     |  _________________________________^
1635 | |         fn starts_with(prefix: &str, case_sensitive: bool, name: &str) -> bool {
1636 | |             case_sensitive && name.starts_with(prefix)
1637 | |                 || !case_sensitive && starts_with_case_insensitive(name, prefix)
...    |
1666 | |         members
1667 | |     }
     | |_____^ associated function was supposed to return data with lifetime `'1` but it is returning data with lifetime `'2`
```

There's like 7 of these errors. Could be a Windows thing? I'm using the nightly toolchain.

2022-05-01 20:26 UTC, nickelc commented
This looks unrelated.

2022-05-01 20:27 UTC, tedtramonte commented
I agree, but it compiles with the manual implementations and won't with the derives. If the derives will work, I'll switch to that and force push. Doesn't both me one way or the other!

2022-05-01 20:39 UTC, nickelc commented
I can't reproduce the error. windows@nightly build job is green.
https://github.com/serenity-rs/serenity/compare/current...nickelc:test-timestamp
https://github.com/nickelc/serenity/runs/6249536227?check_suite_focus=true

2022-05-01 20:46 UTC, tedtramonte commented
Good enough for me. Added the derives and you as a co-author.

2022-05-01 21:20 UTC, acdenisSK approved these changes

2022-05-01 21:20 UTC, merged

2022-05-06 06:36 UTC, nickelc commented
> @nickelc Sorry, not clippy complaining, it's the compiler.
> 
> ```
> error: lifetime may not live long enough
>     --> src\model\guild\mod.rs:1634:33
>      |
> 1630 |           &self,
>      |           - let's call the lifetime of this reference `'1`
> 1631 |           prefix: &str,
>      |                   - let's call the lifetime of this reference `'2`
> ...
> 1634 |       ) -> Vec<(&Member, String)> {
>      |  _________________________________^
> 1635 | |         fn starts_with(prefix: &str, case_sensitive: bool, name: &str) -> bool {
> 1636 | |             case_sensitive && name.starts_with(prefix)
> 1637 | |                 || !case_sensitive && starts_with_case_insensitive(name, prefix)
> ...    |
> 1666 | |         members
> 1667 | |     }
>      | |_____^ associated function was supposed to return data with lifetime `'1` but it is returning data with lifetime `'2`
> ```
> 
> There's like 7 of these errors. Could be a Windows thing? I'm using the nightly toolchain.

I now had a similar error in unrelated `standard` framework code after resolving merge conflicts.
The issues was gone after `cargo clean`. So, i think it's an incremental compilation issue.