Swap ID types to use NonZeroU64 internally
serenity-rs/serenity pull request #1930
Opened 2022-06-01 15:59 UTC by GnomedDev

ID 0 is never a valid id, in the case that if you got a 0 id, you would not be able to use it for the API (eg: fetch it as a user).
Therefore, using `NonZeroU64` instead of `u64` allows for rust to use the niche for enum and other optimizations as seen:

serenity-rs/serenity@next
```
std::mem::size_of::<Guild>(); // 896
std::mem::size_of::<Event>(); // 1552
std::mem::size_of::<Channel>(); // 360
std::mem::size_of::<Message>(); // 1000
std::mem::size_of::<VoiceState>(); // 368
std::mem::size_of::<interaction::Interaction>(); // 1544
```
GnomedDev/serenity@nonzerou64
```
std::mem::size_of::<Guild>(); // 848
std::mem::size_of::<Event>(); // 1504
std::mem::size_of::<Channel>(); // 336
std::mem::size_of::<Message>(); // 960
std::mem::size_of::<VoiceState>(); // 352
std::mem::size_of::<interaction::Interaction>(); // 1496
```

I have been running this on [my bot](https://github.com/GnomedDev/Discord-TTS-Bot) in 30k+ servers and haven't had a single panic or deserialization error, so this is safe to run even on large servers or fancy pre-release features.

2022-06-01 16:26 UTC, kangalioo commented
Id API changes:

- `WhateverId(12345)` => `WhateverId::new(12345)`
- `whatever_id.0` => `whatever_id.get()`

2022-06-04 12:56 UTC, nickelc commented on src/model/id.rs
> +                    Self(NonZeroU64::new(id_as_u64).unwrap())
There is no need to encode the type in the variable name.
```suggestion
                pub fn new(id: u64) -> Self {
                    Self(NonZeroU64::new(id).unwrap())
```

2022-06-04 12:56 UTC, nickelc commented on src/model/id.rs
> +                pub fn as_u64(&self) -> &NonZeroU64 {
the method name differs from the return type.

2022-06-04 12:56 UTC, nickelc commented on src/model/id.rs
> +                pub fn as_mut_u64(&mut self) -> &mut NonZeroU64 {
the method name differs from the return type.

2022-06-06 11:25 UTC, GnomedDev commented
Updated ID API 
- `WhateverId(12345)` => `WhateverId::new(12345)`
- `whatever_id.0` => `whatever_id.get()`
- `whatever_id.as_u64()` => `whatever_id.as_inner()`
- ~~`whatever_id.as_mut_u64`~~
- defining IDs as constants no longer possible (except with unsafe)

2022-06-15 17:41 UTC, acdenisSK requested changes

2022-06-15 17:41 UTC, acdenisSK commented on src/http/client.rs
> +    /// Follow an Announcement Channel to send messages to a target channel.
Unrelated change.

2022-06-15 17:41 UTC, acdenisSK commented on src/model/channel/channel_id.rs
> +    /// Follows the announcement channel
Ditto.

2022-06-20 13:34 UTC, arqunis approved these changes

2022-06-20 13:34 UTC, merged