Add missing fields serenity::model::application types
serenity-rs/serenity pull request #1965
Opened 2022-06-12 21:20 UTC by kangalioo

Fixes #1957, plus I took the liberty of adding Discord docs links to all types in that module, as well as reordering all fields to match Discord docs. And I added `CommandOption::autocomplete` and `MessageInteraction::member` because those fields were present in Discord docs and not in serenity. I briefly tested those two new fields with a one-off bot and `println!()`

2022-06-13 07:39 UTC, nickelc commented on src/model/application/interaction/application_command.rs
> +    // TODO: Why does this field exist? Why a raw json Value when CommandDataOptionValue exists
This is about to change in the `next` branch and is already changed for autocomplete data #1941 
```suggestion
```

2022-06-13 07:42 UTC, nickelc commented on src/model/application/interaction/mod.rs
> +    pub member: Option<PartialMember>,
This is a breaking change because the struct is missing `#[non_exhaustive]`.

2022-06-13 14:38 UTC, kangalio commented on src/model/application/interaction/mod.rs
> +    pub member: Option<PartialMember>,
Rip

Maybe someone else will take it on #1968

2022-06-13 18:30 UTC, GnomedDev requested changes
This has triggered clippy and it is my sole duty to alert you of that.

2022-06-14 07:11 UTC, kangalioo commented
Doubtful whether this fix meaningfully improved codebase quality...

2022-06-14 07:14 UTC, nickelc commented
> Doubtful whether this fix meaningfully improved codebase quality...

clippy is always right ;)

2022-06-14 19:50 UTC, nickelc requested changes

2022-06-14 19:50 UTC, nickelc commented on src/model/application/command.rs
> +    pub description_localizations: Option<std::collections::HashMap<String, String>>,
```suggestion
    /// Localizations of the option description with locale as the key
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description_localizations: Option<std::collections::HashMap<String, String>>,
```

2022-06-14 19:50 UTC, nickelc commented on src/model/application/command.rs
> +    pub name_localizations: Option<std::collections::HashMap<String, String>>,
```suggestion
    /// Localizations of the option name with locale as the key
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
```

2022-06-14 19:50 UTC, nickelc commented on src/model/application/command.rs
> +    pub name_localizations: Option<std::collections::HashMap<String, String>>,
```suggestion
    /// Localizations of the choice name, with locale as key
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
```

2022-06-15 06:35 UTC, kangalioo commented
@nickelc out of curiosity, why are those skip_serializing_if attributes needed?

2022-06-15 09:04 UTC, nickelc commented
The `*_localizations` fields are defined as optional and it can save some bytes if someone wants to serialize the structs.

2022-06-15 15:40 UTC, nickelc approved these changes

2022-06-15 16:09 UTC, merged