Remove Channel::Category
serenity-rs/serenity pull request #2128
Opened 2022-09-08 18:52 UTC by kangalioo

Fixes #1352

Channel categories had two different representations: Channel::Guild(c) with c.kind == ChannelType::Category, and Channel::Category(c). Different parts of serenity used either of these two. This PR unifies serenity to the former.

(I chose the first representation because it results in a lot shorter code, less duplication, is closer to Discord's API, is consistent with how other channel types don't have their own Channel enum variant, makes Channel enum variants be just Guild and Private which is a clean and obvious differentiation.)

2022-09-08 18:54 UTC, kangalioo commented
Presumably also fixes #1513

2022-09-09 21:58 UTC, acdenisSK requested changes

2022-09-09 21:58 UTC, acdenisSK commented on src/cache/event.rs
> +                for (channel_id, _) in &guild.1.channels {
Could you fix the clippy warning here?

2022-09-09 21:58 UTC, acdenisSK commented on src/model/guild/member.rs
> +            if channel.kind != ChannelType::Category {
Ditto.

2022-09-10 18:22 UTC, acdenisSK approved these changes

2022-09-10 18:22 UTC, merged