Add create_forum_thread() in a channel
serenity-rs/serenity pull request #2238
Opened 2022-10-23 18:00 UTC by trkohler

resolve https://github.com/serenity-rs/serenity/issues/2142#issuecomment-1276635360

2022-11-06 09:21 UTC, kangalioo commented
Is this PR ready to be reviewed?

2022-11-16 08:42 UTC, oSumAtrIX requested changes

2022-11-16 08:42 UTC, oSumAtrIX commented on src/http/routing.rs
> +                Cow::from(Route::channel_private_threads(channel_id)),
While this works, the [API specs](https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel) have a separate definition for creating threads in forums. The type of the created thread is PUBLIC_THREAD. Both routes are identical, which is why the current implementation works, but it is better to stick to the specification and create a separate route for creating threads in forums as they have distinct differences to creating a regular, private thread, which the current implementation implies. This route also has different JSON parameters, though this is also not considered in the route of creating a private thread.

2023-03-07 09:27 UTC, trkohler commented
I understand that I can block work with my stale PR, so I would close it since it seems like I am not being good at my time management 😔

2023-03-07 09:27 UTC, closed without merging