Remove ShardManagerMonitor and other gateway cleanup
serenity-rs/serenity pull request #2372
Opened 2023-04-04 04:09 UTC by kangalio

The bulk of this PR is removing ShardManagerMonitor. It was just a background task that received ShardManagerMessage's and called the respective ShardManager function. Now, you can just call the respective ShardManager function directly.

The commits about removing ShardManagerMonitor are marked with `[SMM]`. The other commits do other miscellaneous related clean-up. See commit titles and descriptions for more details.

Largely untested

2023-04-04 14:09 UTC, mkrasnitski commented
Will review this later today. Just quickly noticed that the docs CI job is failing.

2023-04-05 16:52 UTC, mkrasnitski requested changes
I'd say this looks good, aside from a few tiny nits. Untangling the mess that is the gateway code is definitely a good thing (I say this as someone relatively unfamiliar with gateway internals).

Could you provide a sentence or two describing the breaking changes in this PR, for changelog purposes?

2023-04-05 16:52 UTC, mkrasnitski commented on src/client/bridge/gateway/shard_manager.rs
> +            manager: manager.clone(),
```suggestion
            manager: Arc::clone(&manager),
```

To indicate that this is just a refcount increment.

2023-04-05 16:52 UTC, mkrasnitski commented on src/client/bridge/gateway/mod.rs
> +// mod shard_manager_monitor;
```suggestion
```

2023-04-05 16:52 UTC, mkrasnitski commented on src/client/bridge/gateway/shard_queuer.rs
> +            manager: self.manager.clone(),
```suggestion
            manager: Arc::clone(&self.manager),
```
Ditto.

2023-04-05 23:34 UTC, kangalio commented
```
- Removed `InterMessage`, `ShardClientMessage`, `ShardManagerMessage`, `ShardManagerMonitor`, `ShardManagerError`
- Changed `ShardManager::new` return type from `(_, ShardManagerMonitor)` to `(_, UnboundedReceiver<Result<(), GatewayError>)`
  - Instead of calling `ShardManagerMonitor.run()`, you just wait for the return value to arrive via the `UnboundedReceiver`
- Changed `ShardMessenger::new` parameter type from `Sender<InterMessage>` to `Sender<ShardRunnerMessage>`
  - All shard-relevant actions have been centralized into `ShardRunnerMessage`
- Changed `ShardMessenger::send_to_shard` return type from `Result<_, _>` to `()`
  - Errors are now logged in the function directly
- Changed `ShardQueuer`'s and `ShardRunnerOptions`'s field `manage_tx: Sender<ShardManagerMessage>` field to `manager: Arc<Mutex<ShardManager>>`
  - Instead of invoking actions on `ShardManager` by sending messages through a channel, you now invoke methods on `ShardManager` directly
```

Since you said "a sentence or two":
```
`ShardManagerMonitor` has been removed in favor of interacting with `ShardManager` directly.
```

2023-04-08 16:25 UTC, acdenisSK approved these changes

2023-04-08 16:27 UTC, merged

2023-04-09 17:59 UTC, kangalio commented
Here is some additional context about the removed types:

Removed:
- `ShardClientMessage`
    - used to send commands to a ShardRunner. But we already had a type for that: `ShardRunnerMessage`. `ShardClientMessage` existed solely because some shard runner commands ended up in the `ShardManagerMessage` enum for mysterious reasons, so `ShardClientMessage` was an enum over either `ShardRunnerMessage` or `ShardManagerMessage`. This PR moves all shard runner commands into `ShardRunnerMessage`, so you should use that type instead now.
- `InterMessage`
    - an enum that only ever contained `ShardClientMessage`. Use that type directly; or rather it's new replacement `ShardRunnerMessage`.
- `ShardManagerMonitor`
    - received `ShardManagerMessage`'s and propagated them to the actual shard manager. This redundancy has been removed and you can instead call methods on `ShardManager` directly now. All places that previously stored a `Sender<ShardManagerMessage`> now have a `Arc<Mutex<ShardManager>>`.
- `ShardManagerMessage`
    - see above
- `ShardManagerError`
    - duplicated parts of `GatewayError` and was removed in favor of `GatewayError`.

Thanks to @tazz4843 for pointing out the lacking explanation