Move CreateQuickModal to utils
serenity-rs/serenity pull request #2374
Opened 2023-04-07 07:12 UTC by kangalio

All other builder types in that module belong to an HTTP request and clearly represent that request's fields as per Discord documentation. CreateQuickModal doesn't; it's an arbitrary abstraction on top of multiple HTTP requests (and gateway events, violating the pattern that the builder module doesn't have anything to do with gateway). This kind of feature fits better in the utils module

This also opens the possibility to add `serde::Serialize + serde::Deserialize` bounds to the `Builder` trait (cc #2337)

2023-04-07 18:11 UTC, mkrasnitski requested changes
I think this makes sense to do. Got some minor docs changes for you though.

2023-04-07 18:11 UTC, mkrasnitski commented on src/builder/mod.rs
> +/// [`serde::Deserialize`] is useful to be able to store builders locally.
```suggestion
/// Common trait for all HTTP request builders in this module.
```

I don't think the clarification here is necessary.

2023-04-07 18:11 UTC, mkrasnitski commented on src/builder/mod.rs
```suggestion
Serializes a builder's fields and sends the request off the API, returning the response.
```

2023-04-07 18:11 UTC, mkrasnitski commented on src/builder/mod.rs
> +    /// request in.
```suggestion
    /// Additional data that's only required when sending a request off to the API.
```

2023-04-30 15:22 UTC, acdenisSK approved these changes

2023-04-30 15:24 UTC, merged