Support creating standalone public threads
serenity-rs/serenity pull request #2470
Opened 2023-06-22 02:20 UTC by fenhl

Discord's API has two endpoints for creating threads: one for [creating a thread as a reply to a message](https://discord.com/developers/docs/resources/channel#start-thread-from-message) and one for [creating a thread that's not connected to any existing message](https://discord.com/developers/docs/resources/channel#start-thread-without-message). The former only supports creating public threads, but the latter supports both public and private threads. However, serenity did not allow creating public standalone threads. This PR fills that gap, and renames the methods for calling these endpoints to more accurately describe what they do.

When I brought up the missing functionality in the #serenity channel, @arqunis claimed that the “start thread without message” endpoint was only for private threads, pointing to this part of the documentation:

> \* `type` currently defaults to `PRIVATE_THREAD` in order to match the behavior when thread documentation was first published. In a future API version this will be changed to be a required field, with no default.

I believe that this is a misunderstanding of the docs. They say “defaults to `PRIVATE_THREAD`”, not “must be `PRIVATE_THREAD`”. I also tested calling the endpoint manually with `type` set to `PUBLIC_THREAD` and it works as expected.

2023-06-22 02:31 UTC, fenhl commented
CI failure seems to be unrelated.

2023-06-23 04:55 UTC, mkrasnitski requested changes
Just a few minor things. I think mentioning that threads linked to messages will always be public is something we should do, so the docs change to the `create_thread_from_message` methods should be reverted. It might also be worth changing the docs on `CreateThread::kind` to mention how the field is ignored for message threads (as well as how it defaults to private for standalone threads).

2023-06-23 04:55 UTC, mkrasnitski commented on src/http/client.rs
> +    pub async fn create_standalone_thread(
```suggestion
    pub async fn create_thread(
```

Given that `create_thread_from_message` is self-explanatory, no need to include `standalone` in the method name. Same goes for `{ChannelId,GuildChannel}::create_standalone_thread`.

2023-07-06 21:40 UTC, arqunis approved these changes

2023-07-06 21:40 UTC, merged