Fix embed suppression on non-self users when cache is enabled
serenity-rs/serenity pull request #2659
Opened 2023-12-11 15:16 UTC by iulianalexa

This pull request proposes a fix for issue #2644.

2023-12-11 15:21 UTC, GnomedDev requested changes
This is a bad solution, a proposed solution would be to move the check into `EditMessage::execute`, pass along the `author_id` in the Context tuple, and check there while having access to the message flags to check if suppress embeds has been set.

2023-12-11 18:49 UTC, iulianalexa commented
> This is a bad solution, a proposed solution would be to move the check into `EditMessage::execute`, pass along the `author_id` in the Context tuple, and check there while having access to the message flags to check if suppress embeds has been set.

I agree that a more organised solution involves doing the check in execute, however my solution checks the other fields of the struct too in addition to the suppress embeds flag, the thought process being that a request with suppress embeds and a content change would still be invalid.

I would like to know if I should keep using that approach (create a reference struct, check the serialised equality) or if I should just check the flag and let the Discord API handle it.

2023-12-11 18:53 UTC, GnomedDev commented
Why not just compare them directly? Deriving PartialEq might be needed, but it would be a ton more efficent than passing through serde.

2023-12-11 20:34 UTC, iulianalexa commented
If I compare them directly, then is it not fine to do it in `edit` like in the initial proposal, but without the serialisation? Otherwise, I would have to do the cache check inside `execute`, which to me does not make sense considering the original author check was done inside of `edit`. Furthermore, there is one more function calling `execute` that does not use a context (`ChannelId::edit_message`), so I would have to wrap it inside an `Option`, further complicating things and making them look not so nice.

To me it's fine either way, but I thought I'd let you know before I push it.

2023-12-12 11:28 UTC, iulianalexa commented
I have implemented the proposed solution, please let me know if anything should be changed.

2023-12-12 11:39 UTC, alexandruradovici commented on src/builder/edit_message.rs
> +            #[cfg(feature = "cache")]
```suggestion
        #[cfg(feature = "cache")]
        if let Some(user_id) = ctx.2 {
```

I think check should not be done at all if the cache feature is not enabled.

2023-12-12 16:20 UTC, alexandruradovici commented on src/builder/edit_message.rs
> +            }
```suggestion
                if let Some(cache) = cache_http.cache() {
                    let reference_builder = EditMessage::new().suppress_embeds(true);

                    if user_id != cache.current_user().id && self != reference_builder {
                        return Err(Error::Model(ModelError::InvalidUser));
                    }
                }
```

You can delete the inner scope.

2023-12-12 16:30 UTC, iulianalexa commented on src/builder/edit_message.rs
> +            }
Thank you for the suggestion

2024-01-07 17:06 UTC, alexandruradovici commented
Please fix the formatting issue.

2024-01-21 22:56 UTC, arqunis approved these changes

2024-01-21 22:57 UTC, merged