Encode timestamps in RFC3339
serenity-rs/serenity pull request #2665
Opened 2023-12-17 15:07 UTC by Kerollmops

This PR fixes #2664, but I am unsure if it should be unwrapped. It would be better to output an error if we cannot encode them. Also, please tell me if [it is ok to encode in RFC3339 instead of ISO 8601](https://stackoverflow.com/a/522281/1941280).

2023-12-20 17:41 UTC, mkrasnitski requested changes
Thanks for the PR! A few review concerns:

1. This PR changes the signatures of public-facing functions and is therefore breaking. As such, it should target the `next` branch rather than `current`.
2. According to Discord's docs, the [`List Joined Private Archived Threads`](https://discord.com/developers/docs/resources/channel#list-joined-private-archived-threads) endpoint expects the `before` parameter to be a snowflake rather than a timestamp. Since we're dealing with threads here, I think `ChannelId` would be the right type to use.
3. You've missed an endpoint here, in particular the [`List Private Archived Threads`](https://discord.com/developers/docs/resources/channel#list-private-archived-threads) endpoint, which actually _does_ expect a formatted timestamp.

2023-12-20 17:41 UTC, mkrasnitski commented on src/http/client.rs
> +            params.push(("before", before.to_rfc3339().unwrap()));
The implementation of `Display` for `Timestamp` already calls `to_rfc3339`, so we don't actually need to change anything here.

2023-12-20 17:41 UTC, mkrasnitski commented on src/http/client.rs
> +        before: Option<Timestamp>,
This should actually be `Option<ChannelId>`.

2023-12-20 17:41 UTC, mkrasnitski commented on src/model/channel/channel_id.rs
> +        before: Option<Timestamp>,
Same here - should be `Option<ChannelId>`.

2023-12-21 11:11 UTC, Kerollmops commented
Thank you for your review 🙏

I rebased on the `next` branch and used `ChannelId`s instead of `Timestamp`s or `u64`s.

2023-12-21 15:44 UTC, mkrasnitski commented
Ah, sorry for not being clear enough. It's only the `List Joined Private Archived Threads` endpoint that takes a snowflake. The other two endpoints do indeed take timestamps.

2023-12-22 12:53 UTC, Kerollmops commented
Oups, sorry! I just fixed this an squashed the commits.

2023-12-22 15:16 UTC, mkrasnitski approved these changes

2023-12-22 17:16 UTC, arqunis approved these changes

2023-12-22 17:17 UTC, merged