Add missing/undocumented UserPublicFlags
serenity-rs/serenity pull request #2679
Opened 2024-01-01 23:11 UTC by jamesbt365

For the most part this is stealing off discord.py.

https://github.com/Rapptz/discord.py/blob/078b500657c651f72a6ca78ada23332422e23adf/discord/enums.py#L492-L512

The only one I can actually verify what it means/its the right value is spammer, which i have tested and it lines up correctly. If you don't want potentially wrong flags, I can remove all but the spammer flag which I have personally tested.

Wasn't sure how to match up with the current documentation, "flag as" instead of "flag for" in these cases looked a bit weird, so I'm open to suggestions there.

2024-01-01 23:13 UTC, jamesbt365 commented
![image](https://github.com/serenity-rs/serenity/assets/22662856/9182f949-9d24-4600-a3af-812258da38de)
when looking into why the spammer flag isn't documented, I guess discord devs are kinda unreasonable thats why.

2024-01-02 18:35 UTC, mkrasnitski commented
Shouldn't we just adhere to what the Discord docs say? If they don't see a use for undocumented flags to anyone but themselves, should we care?

2024-01-02 18:56 UTC, jamesbt365 commented
I'm not bothered about support for anything but the spammer flag here, I don't understand why Discord doesn't seem the utility here, and what they've said about active users having it being a bug doesn't really line up to the fact that they recently allowed you to filter by it in the new members tab, you could only filter by timeout and dm activity a couple weeks ago and now you can filter by "unusual account activity" too.
![image](https://github.com/serenity-rs/serenity/assets/22662856/3510cbe6-4f67-4e72-a855-ffdc79a69da9)


If what they said was true and they were "fixing it in a couple weeks" and it still happens now either they did fix this, which wouldn't line up to the fact that I saw a user talking with this flag yesterday, or the feature was repurposed into what it is now.
![image](https://github.com/serenity-rs/serenity/assets/22662856/c844b8c3-829c-453f-bdd7-de3eac9037a9)



Why would discord allow you to filter by something that is strictly attached to disabled accounts? Nothing really lines up in regard to that.

Adhering to what the Discord docs say would mean removing a feature that is actually used and has utility behind it.

I'm happy to remove everything but the spammer flag, as I only added the other flags while I was looking into how other libraries handle the flag. I don't want the spammer flag to not be included simply because Discord devs for *some* unclear reason deny documentation for a feature that they are supporting now more than ever.

2024-01-02 19:00 UTC, mkrasnitski commented
Are you sure it's not filtering according to the `unusual_dm_activity_until` member flag? Also, I just realized that field isn't documented anywhere either, so I'm worried if we got the name right.

2024-02-02 22:34 UTC, GnomedDev requested changes
I am happy to merge if these are locked behind the `unstable_discord_api` feature.

2024-02-08 21:07 UTC, jamesbt365 commented
I'm not too confident on the other flags I stole from discord.py, so its probably best I remove those too, I'll get around to this hopefully tomorrow.

2024-02-27 20:39 UTC, jamesbt365 commented
Decided to only do the SPAMMER flag because its the only one I see utility in and can actually prove the documentation of/what it actually does.

2024-02-27 23:19 UTC, merged