add proper serialization for multiple models
serenity-rs/serenity pull request #529
Opened 2019-04-07 18:25 UTC by DarkKirb

Affected Models:

- `GuildEmojiUpdateEvent`
- `Ready`
- `PartialGuild`

This fixes issue #528

2019-04-07 18:37 UTC, arqunis approved these changes

2019-04-08 12:19 UTC, Lakelezz requested changes
Please add tests to make sure this won't happen again!

2019-04-28 09:16 UTC, DarkKirb commented
Added tests, but i need help with one of the tests (it fails for some reason and the error message claims that a sequence is a map)

2019-05-01 11:02 UTC, Lakelezz requested changes
Please revert the formatting on 2848049746870ebf7f6fcae2ea834b28fcbc2a56.

2019-05-06 12:38 UTC, Lakelezz approved these changes

2019-05-06 12:59 UTC, merged