Update `on_mention` to take a `UserId`
serenity-rs/serenity pull request #535
Opened 2019-04-15 16:15 UTC by Celti

With the removal of global `Http` objects, `on_mention` is no longer
authorised for the necessary routes to get the bot's `UserId`.

Directly pass it an `Option<UserId>` instead.

Fixes #530

2019-04-15 16:18 UTC, arqunis approved these changes

2019-04-16 11:37 UTC, Lakelezz requested changes
Thank you for your PR : )

I mentioned some small changes I want to see.
On another note, please change the lowercase word `id` to `ID` - to be consistent with most of Serenity's docs.

2019-04-16 11:37 UTC, Lakelezz commented on src/framework/standard/configuration.rs
> +    /// Whether or not to respond to commands initiated with the mentioned id.
```suggestion
    /// Whether or not to respond to commands initiated with `id_to_mention`.
```

2019-04-16 11:37 UTC, Lakelezz commented on src/framework/standard/configuration.rs
> +    /// Note that this can be used in conjunction with [`prefix`].
While we are at it, turn this into another `**Note**`-block just like the note about ignoring mentions by default.

2019-04-16 11:37 UTC, Lakelezz commented on src/framework/standard/configuration.rs
> +    pub fn on_mention(&mut self, on_mention: Some(UserId)) -> &mut Self {
```suggestion
    pub fn on_mention(&mut self, id_to_mention: Some(UserId)) -> &mut Self {
```

2019-05-03 17:19 UTC, acdenisSK commented
[Cherry-picked and squashed](https://github.com/serenity-rs/serenity/commit/d995fa0e08c67e1a7f217b427d4d9b4dcedaa45b).

2019-05-03 17:19 UTC, closed without merging