Link to ShardMessenger::chunk_guilds from the Guild.members feild
serenity-rs/serenity pull request #683
Opened 2019-08-11 16:03 UTC by Alch-Emi

The [Guild `members` field][1] details that not all users might be available, but doesn't specify that how one might request that the users be made available.  In addition, the method that one would use to accomplish this is kinda hard to find, being on a struct that you can write an entire program without touching once.  Linking to that method from the members field might clarify this a lot.  Sorry for the small PR, but I think this might be an important change (that would certainly have saved me a ton of time and confusion)

[1]: https://docs.rs/serenity/0.6.3/serenity/model/guild/struct.Guild.html#structfield.members

2019-08-12 20:31 UTC, arqunis approved these changes

2019-08-14 18:31 UTC, Lakelezz requested changes
Hello, thanks for your pull request :)

I personally would advice against explaining the function in the first place. The link should suffice. 

My reasoning: If the function ever changes, the user will always have the updated information when clicking on the link. Furthermore, the function's documentation must be good enough to stand on its own ground. 

Therefore, explaining that this functions allows to manually request remaining guild members, should be sufficient.

2019-08-14 19:10 UTC, Alch-Emi commented
Makes sense!  I tend to get a bit overexplainy.  How does this look?

2019-08-15 21:28 UTC, Lakelezz approved these changes

2019-08-15 21:29 UTC, Lakelezz commented
It's fine, thanks : )

2019-08-15 21:29 UTC, merged