Allows `add_file` to support an image URL
serenity-rs/serenity pull request #781
Opened 2020-02-10 20:07 UTC by Elinvynia

This is very shitty, tips on improving appreciated

2020-02-12 23:47 UTC, Flat requested changes

2020-02-12 23:47 UTC, Flat commented on src/http/client.rs
> +                            .file_name(format!("{}.webp", file_num)));
This should use the actual file extension unless you are converting the image to webp format.

2020-02-12 23:47 UTC, Flat commented on src/http/client.rs
> +                    let _ = std::io::copy(&mut *req, &mut picture);
You should handle the result of `std::io::copy` here instead of ignoring it with a `let _` binding

2020-02-16 12:15 UTC, acdenisSK commented on src/http/client.rs
> +                    let req = &mut self.client.get(url).send()?;
```suggestion
                    let mut req = self.client.get(url).send()?;
```

2020-02-16 12:15 UTC, acdenisSK commented on src/http/client.rs
> +                    std::io::copy(&mut *req, &mut picture)?;
```suggestion
                    std::io::copy(&mut req, &mut picture)?;
```

2020-02-16 12:15 UTC, acdenisSK commented on src/http/client.rs
> +                    let parsed_url = match Url::parse(url) {
```suggestion
                    let filename = Url::parse(url)
                        .ok()
                        .and_then(|url| url.path_segments())
                        .and_then(|segments| segments.last())
                        .ok_or_else(|| Error::Url(url.to_string())?;
```

2020-02-16 12:15 UTC, acdenisSK commented on src/http/mod.rs
> +    fn from(s: &'a str) -> AttachmentType<'_> {
```suggestion
    /// Constructs an `AttachmentType` from a string. that may contain a path to a file,
    fn from(s: &'a str) -> AttachmentType<'_> {
```

2020-02-16 18:19 UTC, merged